=== lynx-family/lynx/tools/css_generator/css_define_json_schema/css_define.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "css_define",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "pattern": "^(?![0-9])(?!(--|-\\d))[a-zA-Z0-9\\u00A0-\\uFFFF_-]*$"
      },
      "id": {
        "type": "integer"
      },
      "type": {
        "type": "string"
      },
      "default_value": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "consumption_status": {
        "type": "string",
        "enum": ["layout-wanted", "layout-only", "skip"]
      },
      "desc": {
        "type": "string"
      },
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "values": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string"
            },
            "version": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            },
            "align-type": {
              "type": "string",
              "enum": ["flex-start",  "flex-end", "start", "end"]
            }
          },
          "required": ["value", "version"]
        }
      },
      "links": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            }
          },
          "required": ["url"]
        }
      },
      "note": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "literal": {
              "type": "string"
            },
            "level": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": ["tip", "info", "warning", "danger"]
              }
            }
          },
          "required": ["literal", "level"]
        }
      },
      "example": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "id",
      "type",
      "default_value",
      "version",
      "author",
      "consumption_status",
      "desc"
    ]
  }

=== lynx-family/lynx/tools/css_generator/css_defines/66-animation-timing-function.json
{
    "name": "animation-timing-function",
    "id": 66,
    "type": "timing-function",
    "default_value": "linear",
    "version": "1.0",
    "author": "liyanbo, linxiaosong",
    "consumption_status": "skip",
    "keywords": [
        "linear",
        "ease-in",
        "ease-out",
        "ease-in-ease-out",
        "ease",
        "ease-in-out",
        "square-bezier",
        "cubic-bezier"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/73-border-style.json
{
    "name": "border-style",
    "id": 73,
    "type": "complex",
    "default_value": "solid",
    "author": "liyun",
    "version": "1.0",
    "consumption_status": "skip",
    "keywords": [
        "solid",
        "dashed",
        "dotted",
        "double",
        "groove",
        "ridge",
        "inset",
        "outset",
        "hidden",
        "none"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/103-visibility.json
{
    "name": "visibility",
    "id": 103,
    "type": "enum",
    "default_value": "visible",
    "version": "1.0",
    "author": "wangheyang",
    "desc": "",
    "consumption_status": "skip",
    "values": [
        {
            "value": "hidden",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "visible",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "none",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "collapse",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/89-layout-animation-delete-property.json
{
    "name": "layout-animation-delete-property",
    "id": 89,
    "type": "animation-property",
    "default_value": "opacity",
    "version": "1.0",
    "author": "liyanbo",
    "consumption_status": "skip",
    "keywords": [
        "opacity",
        "scaleX",
        "scaleY",
        "scaleXY"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/209--x-app-region.json
{
    "name": "-x-app-region",
    "id": 209,
    "type": "enum",
    "default_value": "none",
    "version": "2.17",
    "author": "zhoushijie",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "none",
            "version": "2.17",
            "desc": ""
        },
        {
            "value": "drag",
            "version": "2.17",
            "desc": ""
        },
        {
            "value": "no-drag",
            "version": "2.17",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/43-text-align.json
{
    "name": "text-align",
    "id": 43,
    "type": "enum",
    "default_value": "start",
    "version": "1.0",
    "author": "tangruiwen,liting.src",
    "desc": "",
    "consumption_status": "skip",
    "values": [
        {
            "value": "left",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "center",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "right",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "start",
            "version": "2.0",
            "desc": ""
        },
        {
            "value": "end",
            "version": "2.0",
            "desc": ""
        },
        {
            "value": "justify",
            "version": "2.10",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/125-outline-style.json
{
    "name": "outline-style",
    "id": 125,
    "type": "border-style",
    "default_value": "black",
    "version": "1.0",
    "author": "liyun",
    "consumption_status": "skip",
    "keywords": [
        "solid",
        "dashed",
        "dotted",
        "double",
        "groove",
        "ridge",
        "inset",
        "outset",
        "hidden",
        "none"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/62-transform.json
{
    "name": "transform",
    "id": 62,
    "type": "complex",
    "default_value": "",
    "version": "1.0",
    "author": "linxiaosong, wujintian",
    "consumption_status": "skip",
    "keywords": [
        "translate",
        "translateX",
        "translateY",
        "translateZ",
        "translate",
        "translate3d",
        "translate3D",
        "rotate",
        "rotateX",
        "rotateY",
        "rotateZ",
        "scale",
        "scaleX",
        "scaleY"
    ],
    "desc": ""
}
