=== lynx-family/lynx/tools/css_generator/css_define_json_schema/css_define.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "css_define",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "pattern": "^(?![0-9])(?!(--|-\\d))[a-zA-Z0-9\\u00A0-\\uFFFF_-]*$"
      },
      "id": {
        "type": "integer"
      },
      "type": {
        "type": "string"
      },
      "default_value": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "consumption_status": {
        "type": "string",
        "enum": ["layout-wanted", "layout-only", "skip"]
      },
      "desc": {
        "type": "string"
      },
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "values": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string"
            },
            "version": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            },
            "align-type": {
              "type": "string",
              "enum": ["flex-start",  "flex-end", "start", "end"]
            }
          },
          "required": ["value", "version"]
        }
      },
      "links": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            }
          },
          "required": ["url"]
        }
      },
      "note": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "literal": {
              "type": "string"
            },
            "level": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": ["tip", "info", "warning", "danger"]
              }
            }
          },
          "required": ["literal", "level"]
        }
      },
      "example": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "id",
      "type",
      "default_value",
      "version",
      "author",
      "consumption_status",
      "desc"
    ]
  }

=== lynx-family/lynx/tools/css_generator/css_defines/208-hyphens.json
{
    "name": "hyphens",
    "id": 208,
    "type": "enum",
    "default_value": "manual",
    "version": "2.14",
    "author": "zhouchaoying",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "none",
            "version": "2.14",
            "desc": ""
        },
        {
            "value": "manual",
            "version": "2.14",
            "desc": ""
        },
        {
            "value": "auto",
            "version": "2.14",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/117-border-bottom-style.json
{
    "name": "border-bottom-style",
    "id": 117,
    "type": "border-style",
    "default_value": "",
    "version": "1.0",
    "author": "liyun",
    "consumption_status": "skip",
    "keywords": [
        "solid",
        "dashed",
        "dotted",
        "double",
        "groove",
        "ridge",
        "inset",
        "outset",
        "hidden",
        "none"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/87-layout-animation-delete-timing-function.json
{
    "name": "layout-animation-delete-timing-function",
    "id": 87,
    "type": "timing-function",
    "default_value": "linear",
    "version": "1.0",
    "author": "liyanbo",
    "consumption_status": "skip",
    "keywords": [
        "linear",
        "ease-in",
        "ease-out",
        "ease-in-ease-out",
        "ease",
        "ease-in-out",
        "square-bezier",
        "cubic-bezier"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/85-layout-animation-create-property.json
{
    "name": "layout-animation-create-property",
    "id": 85,
    "type": "animation-property",
    "default_value": "opacity",
    "version": "1.0",
    "author": "liyanbo",
    "consumption_status": "skip",
    "keywords": [
        "opacity",
        "scaleX",
        "scaleY",
        "scaleXY"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/45-text-overflow.json
{
    "name": "text-overflow",
    "id": 45,
    "type": "enum",
    "default_value": "clip",
    "version": "1.0",
    "author": "tangruiwen",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "clip",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "ellipsis",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/70-animation-fill-mode.json
{
    "name": "animation-fill-mode",
    "id": 70,
    "type": "complex",
    "default_value": "none",
    "version": "1.0",
    "desc": "",
    "author": "liyanbo, linxiaosong",
    "consumption_status": "skip",
    "values": [
        {
            "value": "none",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "forwards",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "backwards",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "both",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/41-white-space.json
{
    "name": "white-space",
    "id": 41,
    "type": "enum",
    "default_value": "normal",
    "version": "1.0",
    "desc": "",
    "author": "tangruiwen",
    "consumption_status": "skip",
    "values": [
        {
            "value": "normal",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "nowrap",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/207-image-rendering.json
{
    "name": "image-rendering",
    "id": 207,
    "type": "enum",
    "default_value": "auto",
    "version": "2.14",
    "author": "baiqiang",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "auto",
            "version": "2.14",
            "desc": ""
        },
        {
            "value": "crisp-edges",
            "version": "2.14",
            "desc": ""
        },
        {
            "value": "pixelated",
            "version": "2.14",
            "desc": ""
        }
    ]
}
