=== lynx-family/lynx/tools/css_generator/css_define_json_schema/css_define.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "css_define",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "pattern": "^(?![0-9])(?!(--|-\\d))[a-zA-Z0-9\\u00A0-\\uFFFF_-]*$"
      },
      "id": {
        "type": "integer"
      },
      "type": {
        "type": "string"
      },
      "default_value": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "consumption_status": {
        "type": "string",
        "enum": ["layout-wanted", "layout-only", "skip"]
      },
      "desc": {
        "type": "string"
      },
      "keywords": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "values": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "value": {
              "type": "string"
            },
            "version": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            },
            "align-type": {
              "type": "string",
              "enum": ["flex-start",  "flex-end", "start", "end"]
            }
          },
          "required": ["value", "version"]
        }
      },
      "links": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            },
            "desc": {
              "type": "string"
            }
          },
          "required": ["url"]
        }
      },
      "note": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "literal": {
              "type": "string"
            },
            "level": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": ["tip", "info", "warning", "danger"]
              }
            }
          },
          "required": ["literal", "level"]
        }
      },
      "example": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "id",
      "type",
      "default_value",
      "version",
      "author",
      "consumption_status",
      "desc"
    ]
  }

=== lynx-family/lynx/tools/css_generator/css_defines/122-background-clip.json
{
    "name": "background-clip",
    "id": 122,
    "type": "complex",
    "default_value": "border-box",
    "version": "1.0",
    "author": "tangruiwen",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "border-box",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "content-box",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "padding-box",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/189-perspective.json
{
    "name": "perspective",
    "id": 189,
    "type": "length",
    "default_value": "none",
    "version": "2.1",
    "author": "wujintian",
    "consumption_status": "layout-wanted",
    "desc": "",
    "values": [
        {
            "value": "number",
            "version": "2.1",
            "desc": ""
        },
        {
            "value": "vw",
            "version": "2.1",
            "desc": ""
        },
        {
            "value": "vh",
            "version": "2.1",
            "desc": ""
        },
        {
            "value": "default",
            "version": "2.1",
            "desc": ""
        },
        {
            "value": "px",
            "version": "2.1",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/61-font-style.json
{
    "name": "font-style",
    "id": 61,
    "type": "enum",
    "default_value": "normal",
    "version": "1.0",
    "author": "liyun",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "normal",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "italic",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "oblique",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/109-transition-property.json
{
    "name": "transition-property",
    "id": 109,
    "type": "animation-property",
    "default_value": "",
    "version": "1.0",
    "author": "liyanbo,linxiaosong",
    "consumption_status": "skip",
    "keywords": [
        "none",
        "opacity",
        "scaleX",
        "scaleY",
        "scaleXY",
        "width",
        "height",
        "background-color",
        "visibility",
        "left",
        "top",
        "right",
        "bottom",
        "transform",
        "all"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/76-transform-origin.json
{
    "name": "transform-origin",
    "id": 76,
    "type": "complex",
    "default_value": "",
    "author": "wujintian",
    "version": "1.0",
    "consumption_status": "skip",
    "keywords": [
        "left",
        "right",
        "top",
        "bottom",
        "center"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/71-animation-play-state.json
{
    "name": "animation-play-state",
    "id": 71,
    "type": "complex",
    "default_value": "running",
    "version": "1.0",
    "desc": "",
    "author": "liyanbo, linxiaosong",
    "consumption_status": "skip",
    "values": [
        {
            "value": "paused",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "running",
            "version": "1.0",
            "desc": ""
        }
    ]
}

=== lynx-family/lynx/tools/css_generator/css_defines/112-transition-timing-function.json
{
    "name": "transition-timing-function",
    "id": 112,
    "type": "timing-function",
    "default_value": "",
    "version": "1.0",
    "author": "liyanbo,linxiaosong",
    "consumption_status": "skip",
    "keywords": [
        "linear",
        "ease-in",
        "ease-out",
        "ease-in-ease-out",
        "ease",
        "ease-in-out",
        "square-bezier",
        "cubic-bezier"
    ],
    "desc": ""
}

=== lynx-family/lynx/tools/css_generator/css_defines/69-animation-direction.json
{
    "name": "animation-direction",
    "id": 69,
    "type": "complex",
    "default_value": "normal",
    "version": "1.0",
    "author": "liyanbo, linxiaosong",
    "consumption_status": "skip",
    "desc": "",
    "values": [
        {
            "value": "normal",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "reverse",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "alternate",
            "version": "1.0",
            "desc": ""
        },
        {
            "value": "alternate-reverse",
            "version": "1.0",
            "desc": ""
        }
    ]
}
